<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>lab.dragon</groupId>
    <artifactId>a721</artifactId>
    <version>1.1-modbus4j</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
    </parent>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <modbus4j.version>3.1.0.rc1-SNAPSHOT</modbus4j.version>
        <jssc.version>2.9.4</jssc.version>
        <rxtx.version>2.1.7</rxtx.version>
        <maven-shade-plugin.version>3.2.4</maven-shade-plugin.version>
        <main-class>lab.dragon.Main</main-class>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- webSocket -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-configuration-processor</artifactId>-->
<!--            <optional>true</optional>-->
<!--        </dependency>-->

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <!-- netty -->
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
        </dependency>

        <!-- modbus start -->
        <dependency>
            <groupId>com.fazecast</groupId>
            <artifactId>jSerialComm</artifactId>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <groupId>com.infiniteautomation</groupId>
            <artifactId>modbus4j</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.java-native</groupId>
            <artifactId>jssc</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.rxtx</groupId>-->
<!--            <artifactId>rxtx</artifactId>-->
<!--        </dependency>-->
        <!-- modbus end -->
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- modbus start -->
            <dependency>
                <groupId>com.infiniteautomation</groupId>
                <artifactId>modbus4j</artifactId>
                <version>${modbus4j.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-native</groupId>
                <artifactId>jssc</artifactId>
                <version>${jssc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.rxtx</groupId>
                <artifactId>rxtx</artifactId>
                <version>${rxtx.version}</version>
            </dependency>
            <!-- modbus end -->
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>${main-class}</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>